static_files:
	python manage.py collectstatic --noinput

migrate:
	python manage.py makemigrations && python manage.py migrate

add_user:
	python manage.py createsuperuser

run:
	python manage.py runserver 0.0.0.0:8001

